package server;

public enum PayloadType {
<<<<<<< HEAD
	CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_DIRECTION, SYNC_POSITION, CREATE_ROOM, JOIN_ROOM, GET_ROOMS,
	SYNC_CHAIR, SYNC_TICKET, SYNC_GAME_SIZE, PICKUP_TICKET
=======
	CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_DIRECTION, SYNC_POSITION, CREATE_ROOM, JOIN_ROOM, GET_ROOMS
>>>>>>> ad6539c337c0f7fbed6b72a17dafb4e21fa039e9
}